apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sqs-job-callback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sqs-job-callback
  template:
    metadata:
      labels:
        app: aws-sqs-job-callback
    spec:
      containers:
        - name: aws-sqs-job-callback
          image: aws-sqs-job-callback:test01
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: aws-sqs-job-callback
spec:
  selector:
    app: aws-sqs-job-callback
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
