---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-sqs-job-worker-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-sqs-job-worker-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-sqs-job-worker-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: aws-sqs-job-worker-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: aws-sqs-job-worker-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sqs-job-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sqs-job-worker
  template:
    metadata:
      labels:
        app: aws-sqs-job-worker
    spec:
      serviceAccountName: aws-sqs-job-worker-sa
      containers:
        - name: aws-sqs-job-worker
          image: aws-sqs-job-worker:test10
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_ACCESS_KEY_ID
              value: { your-access-key-id }
            - name: AWS_SECRET_ACCESS_KEY
              value: { your-secret-access-key }
            - name: AWS_REGION
              value: { your-region }
            - name: AWS_SQS_REGION
              value: { your-sqs-region }
            - name: AWS_SQS_QUEUE
              value: { your-queue-url }
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REDIS_ENDPOINT
              value: redis-service:6379
            - name: REDIS_DB
              value: "0"
