# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - "*"
  paths:
    exclude:
      - README.md
      - VERSION.md
      - .gitignore
      - .gitattributes
      - .editorconfig
      - example/*

pool: Default

variables:
  REPOSITORY: ops/aws-sqs-job-worker
  SERVICE_NAMESPACE: ops
  SERVICE_NAME: aws-sqs-job-worker

resources:
  repositories:
    - repository: ops-pipelines
      type: git
      name: OPS/ops-pipelines

steps:
  - template: templates/commit-sha.yaml@ops-pipelines

  - script: |
      latest_tag=$(git describe --tags --abbrev=0)
      if [ $? -eq 0 ]; then
          echo "Latest Git tag: $latest_tag"
      else
          echo "No tags found in this repository, set to v0.1.0"
          latest_tag=v0.1.0
      fi

      echo "##vso[task.setvariable variable=IMAGE_TAG]$latest_tag"
    env: { sourceVersion: $(Build.SourceVersion) }
    displayName: Create image tag variable

  - template: templates/docker-build.yaml@ops-pipelines
    parameters:
      dockerfile: build/Dockerfile
      repository: $(REPOSITORY)
      image_tag: "$(IMAGE_TAG)"
      multi_platform: true

  # - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  #     - template: templates/cd-trigger.yaml@ops-pipelines
  #       parameters:
  #         deployment_project_name: OPS
  #         deployment_git_repo_name: vr-ops-kops
  #         namespace: $(SERVICE_NAMESPACE)
  #         service_folder: $(SERVICE_NAME)
  #         environment: dev
  #         image_name: $(SERVICE_NAME)-image
  #         build_tag: $(IMAGE_TAG)
  #         only_env: $(ONLY_ENV)
  #         config_path: deployments/dev.env
